-- begin SCHEDULER_SCHEDULE
alter table SCHEDULER_SCHEDULE add constraint FK_SCHEDULER_SCHEDULE_ON_SUBJECT foreign key (SUBJECT_ID) references SCHEDULER_SUBJECT(ID)^
alter table SCHEDULER_SCHEDULE add constraint FK_SCHEDULER_SCHEDULE_ON_TEACHER foreign key (TEACHER_ID) references SCHEDULER_TEACHER(ID)^
create index IDX_SCHEDULER_SCHEDULE_ON_SUBJECT on SCHEDULER_SCHEDULE (SUBJECT_ID)^
create index IDX_SCHEDULER_SCHEDULE_ON_TEACHER on SCHEDULER_SCHEDULE (TEACHER_ID)^
-- end SCHEDULER_SCHEDULE
-- begin SCHEDULE_STUDENT_LINK
alter table SCHEDULE_STUDENT_LINK add constraint FK_SCHSTU_ON_SCHEDULE foreign key (SCHEDULE_ID) references SCHEDULER_SCHEDULE(ID)^
alter table SCHEDULE_STUDENT_LINK add constraint FK_SCHSTU_ON_STUDENT foreign key (STUDENT_ID) references SCHEDULER_STUDENT(ID)^
-- end SCHEDULE_STUDENT_LINK
