###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.dbmsType = hsql

cuba.springContextConfig = +com/company/scheduler/spring.xml

cuba.persistenceConfig = +com/company/scheduler/persistence.xml

cuba.metadataConfig = +com/company/scheduler/metadata.xml

cuba.viewsConfig = +com/company/scheduler/views.xml

cuba.mainMessagePack = +com.company.scheduler.core

cuba.keyForSecurityTokenEncryption = dX1Qc9SbeFfH8rhG

cuba.anonymousSessionId = e6c7ec19-81a5-d4f4-1498-f2eb489a5b60

###############################################################################
#                                  Other                                      #
###############################################################################

cuba.webContextName = app-core
cuba.availableLocales = Russian|ru;English|en
cuba.localeSelectVisible = false

cuba.dataSourceProvider = application
cuba.dataSource.username = sa
cuba.dataSource.password =
cuba.dataSource.dbName = scheduler-147301
cuba.dataSource.host = localhost
cuba.dataSource.port = 9010

#directory for report archive import
app.reports.path=${user.dir}/../../../reportArchive
