###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.springContextConfig = +com/company/scheduler/web-spring.xml

cuba.dispatcherSpringContextConfig = +com/company/scheduler/web-dispatcher-spring.xml

cuba.persistenceConfig = +com/company/scheduler/persistence.xml

cuba.metadataConfig = +com/company/scheduler/metadata.xml

cuba.viewsConfig = +com/company/scheduler/views.xml

cuba.windowConfig = +com/company/scheduler/web-screens.xml

cuba.menuConfig = +com/company/scheduler/web-menu.xml

cuba.permissionConfig = +com/company/scheduler/web-permissions.xml

cuba.mainMessagePack = +com.company.scheduler.web

cuba.anonymousSessionId = e6c7ec19-81a5-d4f4-1498-f2eb489a5b60

cuba.creditsConfig = +

###############################################################################
#                                  Other                                      #
###############################################################################

# Middleware connection
cuba.connectionUrlList = http://localhost:8080/app-core

# Set to false if the middleware works on different JVM
cuba.useLocalServiceInvocation = true

cuba.webContextName = app
cuba.availableLocales = Russian|ru;English|en
cuba.localeSelectVisible = false
cuba.web.theme = hover